# Generated by Django 5.2.8 on 2025-11-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
